/*
بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيْمِ  ﷺ InshaAllah
*/

import type { Metadata } from "next";
import MainSlider from "@/components/ui/section/MainSlider";
import IconBoxes from "@/components/ui/section/IconBoxes";
import CategorySection from "@/components/ui/section/CategorySection";
import FeaturedProductsSection from "@/components/ui/section/FeaturedProductsSection";
import RecommendedProducts from "@/components/ui/section/RecommendedProducts";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
    <main>
      <MainSlider />
      <IconBoxes />
      <CategorySection />
      <FeaturedProductsSection newProducts={generateProducts(8, 'New')} mostLovedProducts={generateProducts(8, 'Most Loved')} hotSalesProducts={generateProducts(8, 'Hot Sales')} discountedProducts={generateProducts(8, 'Discounted')} recommendedProducts={generateProducts(8, 'Recommended')} />
      {/* <RecommendedProducts title="Recommended For You" viewAllLink="/products" products={generateProducts(5, 'Recommended')} /> */}
    </main>
    </>
  );
}


function generateProducts(count: number, type: string) {
  return Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    name: `${type} Product ${i + 1}`,
    slug: `${type.toLowerCase()}-product-${i + 1}`,
    imageUrl: `/images/product.svg`,
    price: 19.99 + i * 10,
    originalPrice: type === 'Discounted' ? (19.99 + i * 10) * 1.25 : undefined,
    category: ['Electronics', 'Clothing', 'Home & Kitchen', 'Beauty'][i % 4],
    rating: 3 + Math.random() * 2,
    isNew: type === 'New',
    isHot: type === 'Hot Sales',
    discountPercentage: type === 'Discounted' ? 20 : undefined
  }));
};