/*
بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيْمِ  ﷺ InshaAllah
*/
export const productsMap = new Map<string, string>([
    ["all", "All Products"], 
    ["new", "Latest Products"], 
    ["mostLoved", "Most Loved"],
    ["hotSales", "Best Sellers"], 
    ["featured", "Featured Products"],
    ["recommended", "Recommended Products"],
    ["in-stock", "In Stock"],
    ["out-of-stock", "Out of Stock"],
    ["discounted", "On Discount"],
    ["on-promotion", "On Promotion"],
    ["t-shirts", "T-shirts"],
    ["jerseys-pullovers", "Jerseys & Pullovers"],
    ["sweaters", "Sweaters"],
    ["jackets", "Jackets"],
    ["sweatpants", "Sweatpants"],
    ["sweatshirts", "Sweatshirts"],
    ["leggings", "Leggings"],
    ["polo-shirts", "Polo shirts"],
    ["tops", "Tops"],
    ["tank-tops", "Tank tops"],
    ["shirts", "Shirts"],
    ["trousers", "Trousers"],
    ["denim", "Denim"],
    ["jeans", "Jeans"],
    ["dresses", "Dresses"],
    ["skirts", "Skirts"],
    ["shorts", "Shorts"],
    ["blouses", "Blouses"],
    ["casual-wear", "Casual wear"],
    ["formal-wear", "Formal wear"],
    ["workwear", "Workwear"],
    ["sports-wear", "Sports wear"],
    ["salwar-kameez", "Salwar Kameez"],
    ["kurta", "Kurta"],
    ["saree", "Saree"],
    ["panjabi", "Panjabi"],
    ["frock", "Frock"],
    ["jubba-thobe", "Jubba & thobe"],
    ["jump-suit-rompers", "Jump suit & rompers"],
    ["lingerie", "Lingerie"],
    ["maternity-clothes", "Maternity clothes"],
    ["night-dresses", "Night dresses"],
    ["bath-robes", "Bath Robes"],
    ["beach-wear", "Beach wear"],
    ["uniforms", "Uniforms"],
    ["rain-wear", "Rain wear"],
    ["thermal-wear", "Thermal wear"],
    ["yoga-wear", "Yoga wear"],
    ["bed-linen", "Bed linen"],
    ["bed-sheets", "Bed sheets"],
    ["bedroom-textiles", "Bedroom textiles"],
    ["bath-linen", "Bath linen"],
    ["carpets", "Carpets"],
    ["rugs", "Rugs"],
    ["blankets", "Blankets"],
    ["kitchen-linen", "Kitchen linen"],
    ["curtains", "Curtains"],
    ["cushions", "Cushions"],
    ["cushion-cover", "Cushion cover"],
    ["large-appliances", "Large Appliances"],
    ["small-appliances", "Small Appliances"],
    ["cooling-heating", "Cooling & Heating"],
    ["kitchen-appliances", "Kitchen Appliances"],
    ["other-home-appliances", "Other Home Appliances"],
    ["air-conditioners", "Air Conditioners"],
    ["geysers-water-heaters", "Geysers/Water Heaters"],
    ["exhaust-fans", "Exhaust Fans"],
    ["microwave-ovens", "Microwave Ovens"],
    ["blenders-mixer-grinders", "Blenders/Mixer Grinders"],
    ["electric-heaters", "Electric Heaters"],
    ["switches-sockets", "Switches & Sockets"],
    ["plugs-adapters", "Plugs & Adapters"],
    ["lighting", "Lighting"],
    ["batteries", "Batteries"],
    ["modules-boards", "Modules & Boards"],
    ["digital-meters", "Digital Meters"],
    ["extension-leads", "Extension Leads"],
    ["ties-clips", "Ties & Clips"],
    ["calling-bells", "Calling Bells"],
    ["multi-plugs", "Multi Plugs"],
    ["transformers", "Transformers"],
    ["switchgear", "Switchgear"],
    ["generators", "Generators"],
    ["cables", "Cables"],
    ["circuit-breakers", "Circuit Breakers"],
    ["panels", "Panels"],
    ["wires", "Wires"],
    ["fans", "Fans"],
    ["water-heaters", "Water Heaters"],
    ["water-pumps", "Water Pumps"],
    ["water-filters", "Water Filters"],
    ["water-purifiers", "Water Purifiers"],
    ["refrigerators", "Refrigerators"],
    ["dishwashers", "Dishwashers"],
    ["coffee-makers", "Coffee Makers"],
    ["toasters", "Toasters"],
    ["food-processors", "Food Processors"],
    ["rice-cookers", "Rice Cookers"],
    ["pressure-cookers", "Pressure Cookers"],
    ["kitchen-hoods", "Kitchen Hoods"],
    ["induction-cooktops", "Induction Cooktops"],

    ["skin-care", "Skin Care"],
["cleansers", "Cleansers"],
["facial-cleansers", "Facial cleansers"],
["body-washes", "Body washes"],
["soaps", "Soaps"],
["makeup-removers", "Makeup removers"],
["moisturizers", "Moisturizers"],
["facial-moisturizers", "Facial moisturizers"],
["body-lotions", "Body lotions"],
["hand-creams", "Hand creams"],
["lip-balms", "Lip balms"],
["serums", "Serums"],
["toners", "Toners"],
["exfoliators", "Exfoliators"],
["chemical-exfoliants", "Chemical exfoliants"],
["physical-exfoliants", "Physical exfoliants"],
["face-masks", "Face masks"],
["sunscreen", "Sunscreen"],
["sunscreen-lotions", "Sunscreen lotions"],
["sunscreen-sprays", "Sunscreen sprays"],
["eye-creams", "Eye creams"],
["anti-aging-products", "Anti-aging products"],
["hair-care", "Hair Care"],
["shampoos", "Shampoos"],
["conditioners", "Conditioners"],
["hair-styling-products", "Hair styling products"],
["hair-sprays", "Hair sprays"],
["gels", "Gels"],
["mousses", "Mousses"],
["hair-treatments", "Hair treatments"],
["hair-oils", "Hair oils"],
["hair-masks", "Hair masks"],
["hair-coloring-products", "Hair coloring products"],
["makeup", "Makeup (Cosmetics)"],
["face-makeup", "Face makeup"],
["foundation", "Foundation"],
["concealer", "Concealer"],
["blush", "Blush"],
["bronzer", "Bronzer"],
["highlighter", "Highlighter"],
["eye-makeup", "Eye makeup"],
["mascara", "Mascara"],
["eye-shadow", "Eye shadow"],
["eyeliner", "Eyeliner"],
["eyebrow-products", "Eyebrow products"],
["lip-makeup", "Lip makeup"],
["lipstick", "Lipstick"],
["lip-gloss", "Lip gloss"],
["lip-liner", "Lip liner"],
["oral-care", "Oral Care"],
["toothpaste", "Toothpaste"],
["toothbrushes", "Toothbrushes"],
["mouthwash", "Mouthwash"],
["dental-floss", "Dental floss"],
["nail-care", "Nail Care"],
["nail-polish", "Nail polish"],
["nail-polish-remover", "Nail polish remover"],
["nail-care-tools", "Nail care tools"],
["nail-files", "Nail files"],
["cuticle-pushers", "Cuticle pushers"],
["body-care", "Body Care"],
["body-lotions-and-creams", "Body lotions and creams"],
["deodorants-and-antiperspirants", "Deodorants and antiperspirants"],
["body-washes-and-soaps", "Body washes and soaps"],
["hair-removal-products", "Hair removal products"],
["shaving-creams", "Shaving creams"],
["razors", "Razors"],
["waxing-products", "Waxing products"],
["depilatory-creams", "Depilatory creams"],
["fragrances", "Fragrances"],
["perfumes", "Perfumes"],
["colognes", "Colognes"],
["other-personal-care-products", "Other Personal Care Products"],
["feminine-hygiene-products", "Feminine hygiene products"],
["baby-care-products", "Baby care products"],
["sun-care-products", "Sun care products"],
["eye-care-products", "Eye care products"],
["eye-drops", "Eye drops"],
["hand-sanitizers", "Hand sanitizers"],
["sports-and-outdoors", "Sports & Outdoors"],
["team-sports", "Team Sports"],
["basketball", "Basketball"],
["soccer", "Soccer"],
["football", "Football"],
["baseball", "Baseball"],
["volleyball", "Volleyball"],
["hockey", "Hockey"],
["individual-sports", "Individual Sports"],
["running", "Running"],
["swimming", "Swimming"],
["cycling", "Cycling"],
["tennis", "Tennis"],
["golf", "Golf"],
["yoga-and-pilates", "Yoga & Pilates"],
["fitness", "Fitness"],
["strength-training", "Strength Training"],
["cardio", "Cardio"],
["exercise-machines", "Exercise Machines"],
["weights", "Weights"],
["outdoor-recreation", "Outdoor Recreation"],
["camping-and-hiking", "Camping & Hiking"],
["tents", "Tents"],
["sleeping-bags", "Sleeping Bags"],
["backpacks", "Backpacks"],
["hiking-boots", "Hiking Boots"],
["fishing", "Fishing"],
["fishing-rods", "Fishing Rods"],
["fishing-reels", "Fishing Reels"],
["fishing-tackle", "Fishing Tackle"],
["hunting", "Hunting"],
["archery", "Archery"],
["shooting-sports", "Shooting Sports"],
["water-sports", "Water Sports"],
["surfing", "Surfing"],
["kayaking", "Kayaking"],
["paddleboarding", "Paddleboarding"],
["diving-and-snorkeling", "Diving & Snorkeling"],
["winter-sports", "Winter Sports"],
["skiing", "Skiing"],
["snowboarding", "Snowboarding"],
["snowshoes", "Snowshoes"],
["skating", "Skating"],
["outdoor-clothing", "Outdoor Clothing"],
["athletic-apparel", "Athletic Apparel"],
["sports-shoes", "Sports Shoes"],
["sports-accessories", "Sports Accessories"],
["sports-electronics", "Sports Electronics"],
["gps-devices", "GPS Devices"],
["fitness-trackers", "Fitness Trackers"],
["action-cameras", "Action Cameras"],
["sports-nutrition", "Sports Nutrition"],
["protein-powders", "Protein Powders"],
["sports-drinks", "Sports Drinks"],
["energy-bars", "Energy Bars"],
["cycling-accessories", "Cycling Accessories"],
["skateboarding-and-scooters","Skateboarding & Scooters"],
["rollerblading","Rollerblading"],
["climbing","Climbing"],
["equestrian","Equestrian"],
["darts","Darts"],
["billiards","Billiards"],
["books-and-stationery", "Books & Stationery"],
  ["books", "Books"],
  ["fiction", "Fiction"],
  ["novels", "Novels"],
  ["mystery", "Mystery"],
  ["thriller", "Thriller"],
  ["science-fiction", "Science Fiction"],
  ["fantasy", "Fantasy"],
  ["romance", "Romance"],
  ["historical-fiction", "Historical Fiction"],
  ["young-adult", "Young Adult"],
  ["childrens-books", "Children's Books"],
  ["nonfiction", "Nonfiction"],
  ["biographies", "Biographies"],
  ["autobiographies", "Autobiographies"],
  ["history", "History"],
  ["science", "Science"],
  ["self-help", "Self-Help"],
  ["cookbooks", "Cookbooks"],
  ["travel-guides", "Travel Guides"],
  ["reference-books", "Reference Books"],
  ["textbooks", "Textbooks"],
  ["comic-books", "Comic Books"],
  ["graphic-novels", "Graphic Novels"],
  ["magazines", "Magazines"],
  ["newspapers", "Newspapers"],
  ["stationery", "Stationery"],
  ["writing-instruments", "Writing Instruments"],
  ["pens", "Pens"],
  ["pencils", "Pencils"],
  ["markers", "Markers"],
  ["highlighters", "Highlighters"],
  ["paper-products", "Paper Products"],
  ["notebooks", "Notebooks"],
  ["journals", "Journals"],
  ["diaries", "Diaries"],
  ["loose-leaf-paper", "Loose Leaf Paper"],
  ["printer-paper", "Printer Paper"],
  ["cards-and-envelopes", "Cards & Envelopes"],
  ["art-supplies", "Art Supplies"],
  ["paints", "Paints"],
  ["brushes", "Brushes"],
  ["canvas", "Canvas"],
  ["drawing-pads", "Drawing Pads"],
  ["coloring-books", "Coloring Books"],
  ["craft-supplies", "Craft Supplies"],
  ["adhesives", "Adhesives"],
  ["scissors", "Scissors"],
  ["office-supplies", "Office Supplies"],
  ["organizers", "Organizers"],
  ["folders", "Folders"],
  ["binders", "Binders"],
  ["calendars", "Calendars"],
  ["planners", "Planners"],
  ["desk-accessories", "Desk Accessories"],
  ["educational-resources", "Educational Resources"],
  ["school-supplies", "School Supplies"],

  ["toys-and-games", "Toys & Games"],
  ["action-figures", "Action Figures"],
  ["dolls", "Dolls"],
  ["building-toys", "Building Toys"],
  ["lego", "LEGO"],
  ["building-blocks", "Building Blocks"],
  ["puzzles", "Puzzles"],
  ["jigsaw-puzzles", "Jigsaw Puzzles"],
  ["brain-teasers", "Brain Teasers"],
  ["board-games", "Board Games"],
  ["card-games", "Card Games"],
  ["dice-games", "Dice Games"],
  ["video-games", "Video Games"],
  ["console-games", "Console Games"],
  ["pc-games", "PC Games"],
  ["mobile-games", "Mobile Games"],
  ["outdoor-toys", "Outdoor Toys"],
  ["ride-on-toys", "Ride-On Toys"],
  ["sports-toys", "Sports Toys"],
  ["water-toys", "Water Toys"],
  ["remote-control-toys", "Remote Control Toys"],
  ["rc-cars", "RC Cars"],
  ["rc-airplanes", "RC Airplanes"],
  ["plush-toys", "Plush Toys"],
  ["stuffed-animals", "Stuffed Animals"],
  ["educational-toys", "Educational Toys"],
  ["stem-toys", "STEM Toys"],
  ["learning-toys", "Learning Toys"],
  ["arts-and-crafts", "Arts & Crafts"],
  ["drawing-and-painting", "Drawing & Painting"],
  ["modeling-clay", "Modeling Clay"],
  ["craft-kits", "Craft Kits"],
  ["collectibles", "Collectibles"],
  ["trading-cards", "Trading Cards"],
  ["model-kits", "Model Kits"],
  ["party-games", "Party Games"],
  ["family-games", "Family Games"],
  ["strategy-games", "Strategy Games"],
  ["role-playing-games", "Role-Playing Games"],
  ["toy-vehicles", "Toy Vehicles"],
  ["diecast-cars", "Diecast Cars"],
  ["toy-trains", "Toy Trains"],
  ["toy-planes", "Toy Planes"],
  ["infant-and-toddler-toys", "Infant & Toddler Toys"],
  ["musical-toys", "Musical Toys"],
  ["play-sets", "Play Sets"],
  ["dollhouses", "Dollhouses"],
  ["toy-kitchens", "Toy Kitchens"],
  ["science-kits", "Science Kits"],
  ["magic-tricks", "Magic Tricks"],
  ["puzzles-and-games", "Puzzles & Games"],
  ["electronic-toys", "Electronic Toys"],

  ["jewelry-and-accessories", "Jewelry & Accessories"],
  ["jewelry", "Jewelry"],
  ["necklaces", "Necklaces"],
  ["pendants", "Pendants"],
  ["earrings", "Earrings"],
  ["rings", "Rings"],
  ["bracelets", "Bracelets"],
  ["anklets", "Anklets"],
  ["brooches", "Brooches"],
  ["jewelry-sets", "Jewelry Sets"],
  ["fine-jewelry", "Fine Jewelry"],
  ["gold-jewelry", "Gold Jewelry"],
  ["silver-jewelry", "Silver Jewelry"],
  ["diamond-jewelry", "Diamond Jewelry"],
  ["pearl-jewelry", "Pearl Jewelry"],
  ["fashion-jewelry", "Fashion Jewelry"],
  ["beaded-jewelry", "Beaded Jewelry"],
  ["costume-jewelry", "Costume Jewelry"],
  ["body-jewelry", "Body Jewelry"],
  ["watches", "Watches"],
  ["men-watches", "Men's Watches"],
  ["women-watches", "Women's Watches"],
  ["smartwatches", "Smartwatches"],
  ["accessories", "Accessories"],
  ["scarves", "Scarves"],
  ["shawls", "Shawls"],
  ["hats", "Hats"],
  ["gloves", "Gloves"],
  ["belts", "Belts"],
  ["wallets", "Wallets"],
  ["handbags", "Handbags"],
  ["purses", "Purses"],
  ["backpacks", "Backpacks"],
  ["sunglasses", "Sunglasses"],
  ["hair-accessories", "Hair Accessories"],
  ["ties", "Ties"],
  ["cufflinks", "Cufflinks"],
  ["keychains", "Keychains"],
  ["jewelry-boxes", "Jewelry Boxes"],
  ["jewelry-cleaning-supplies", "Jewelry Cleaning Supplies"],
  ["fashion-accessories", "Fashion Accessories"]
]);